- action:
  - alias: ''
    data:
      message: "\U0001F4C8 \U0001F321 CPU:  {{ states.sensor.cpu_temp.state}}\xB0\
        C, {{now().strftime('%a %d %b, alle ore %k:%M')}}"
      title: "\u26A0\uFE0F\U0001F321 CPU  {{ states.sensor.cpu_temp.state}}\xB0C"
    service: persistent_notification.create
  - data:
      message: "\U0001F4C8 \U0001F321 CPU:  {{ states.sensor.cpu_temp.state}}\xB0\
        C, {{now().strftime('%a %d %b, alle ore %k:%M')}}"
      title: "\u26A0\uFE0F\U0001F321CPU  {{ states.sensor.cpu_temp.state}}\xB0C"
    service: notify.HASS_notifier_bot
  alias: Alert Temperatura Processore
  id: '1496856022680'
  trigger:
  - above: '60'
    entity_id: sensor.cpu_temp
    platform: numeric_state
- action:
  - data:
      message: Sappilo!
      title: "Michele \xE8 a casa"
    service: persistent_notification.create
  alias: Quando Michele Rientra
  id: '1496909439685'
  trigger:
  - entity_id: device_tracker.michele_iphone
    from: not_home
    platform: state
    to: home
- action:
  - alias: ''
    data:
      message: ' '
      notification_id: MQTT crash
      title: Mosquitto crashed!
    service: persistent_notification.create
  alias: Mqtt Crash
  id: '1497105053826'
  trigger:
  - entity_id: sensor.process_mosquitto
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      message: "\U0001F4BE Disco quasi pieno ({{ states.sensor.disk_use_.state}}%)"
      title: "\u26A0\uFE0F \U0001F4BE Spazio disco "
    service: persistent_notification.create
  alias: Alert Spazio disco
  id: '1497105673590'
  trigger:
  - above: '80'
    entity_id: sensor.disk_use_
    platform: numeric_state
- action:
  - data:
      message: Update disponibile
      title: "\u26A0\uFE0F  Update "
    service: persistent_notification.create
  alias: Nuovo update disponibile
  id: '1497615332660'
  trigger:
  - entity_id: updater.updater
    platform: state
#- action:
#  - data:
#      message: ''
#      title: "\u26A0\uFE0F  Ottimo"
#    service: persistent_notification.create
#  - alias: ''
#    data:
#      message: ottimo
#      title: "\u26A0\uFE0F Home Assistant \xE8 appena ripartito"
#    service: notify.HASS_notifier_bot
#  alias: Rebooted
#  id: '1499764835282'
#  trigger:
#  - event_type: homeassistant_start
#    platform: event
