- platform: nmap_tracker
  hosts: 10.0.0.100-253
  track_new_devices: false
  interval_seconds: 60
  exclude:
   - 10.0.0.136
  consider_home: 800

- platform: ping
  hosts:
    DVR: 10.0.0.179
  count: 5
